### PR TITLE
Fix macOS related issues

### PR DESCRIPTION
**Pull request by k06a**

### CODE REVIEW

**Comment by k06a** [comment]
Not yet solved linker error

**Comment by Creepsky** [comment]
Nice, finally someone with macOS :)
Thanks for the fixes, looks good!
(related to #125)

**Comment by k06a** [comment]
@Creepsky sorry, looks like I've changed formatting a little bit.

**Comment by Creepsky** [comment]
@k06a no problem, refactoring can be done later.

**Pull request merged**
