### PR TITLE
Add missing flag NDEBUG to CMakeLists.txt

### PR DESCRIPTION
**Pull request by k06a**
Fixing this issue: https://github.com/Creepsky/creepMiner/issues/131

### CODE REVIEW

**Comment by k06a** [comment]
Not finished yet...

**Comment by k06a** [comment]
Updated documentation about:
```
cmake -DCMAKE_BUILD_TYPE=Release .
make
```

**Comment by k06a** [comment]
But faced new problem:
```
00:37:48: --------------------------------------------------
00:37:48: MWTK-BKY8-ZJ2W-37NKN: nonce found (7m 9d 01:00:46)
00:37:48: 	nonce: 171210
00:37:48: 	in: /Volumes/HDD1/1893347256907199281_0_3801088_3801088
00:37:48: MWTK-BKY8-ZJ2W-37NKN: nonce on the way (7m 9d 01:00:46)
00:37:48: Submit-loop 1 (7m 9d 01:00:46)
00:37:48: MWTK-BKY8-ZJ2W-37NKN: nonce submitted (7m 9d 01:00:46)
00:37:48: 	nonce: 171210
00:37:48: 	in /Volumes/HDD1/1893347256907199281_0_3801088_3801088
00:37:49: JSON confirmation (7m 9d 01:00:46)
00:37:49: 	
00:37:49: MWTK-BKY8-ZJ2W-37NKN: error on submitting nonce! (7m 9d 01:00:46)
00:37:49: MiniMiner: nonce found (1m 6d 01:38:37)
00:37:49: 	nonce: 4581846
00:37:49: 	in: /Volumes/HDD2/1893347256907199281_3801088_3801088_3801088
00:37:49: MiniMiner: nonce on the way (1m 6d 01:38:37)
00:37:49: Submit-loop 1 (1m 6d 01:38:37)
00:37:49: MiniMiner: nonce submitted (1m 6d 01:38:37)
00:37:49: 	nonce: 4581846
00:37:49: 	in /Volumes/HDD2/1893347256907199281_3801088_3801088_3801088
00:37:49: JSON confirmation (1m 6d 01:38:37)
00:37:49: 	
00:37:49: MiniMiner: error on submitting nonce! (1m 6d 01:38:37)
```

HTTP Request:
```
POST /burst?requestType=submitNonce&nonce=171210&accountId=1893347256907199281 HTTP/1.1
X-Capacity: 1856
X-PlotsHash: 5e018d95d450272d2c6c3deb228e5cf7ca92862a
X-Miner: creepMiner 1.6.0 BSD x64
X-Deadline: 18925246
X-Plotfile: /Volumes/HDD1/1893347256907199281_0_3801088_3801088
Connection: Close
Content-Length: 0
Host: pool.burstcoin.ro
```

HTTP Response:
```
HTTP/1.1 200 OK
Date: Sat, 10 Jun 2017 21:37:49 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Set-Cookie: __cfduid=d24ef07f87a322088ade1f44009e49a291497130668; expires=Sun, 10-Jun-18 21:37:48 GMT; path=/; domain=.burstcoin.ro; HttpOnly
X-Powered-By: Express
Vary: Accept-Encoding
Server: cloudflare-nginx
CF-RAY: 36cf7958a1eb4ed8-DME

25
submitNonce & getMiningInfo API Call 
4
Only
0
```

Request and response are from same connection, proof:

**Comment by k06a** [comment]
Submission is okay, why miner reported submission error @Creepsky?

**Comment by k06a** [comment]
Changed miner configuration a little bit (port 8080):
```
"urls" : {
    "miningInfo" : "http://pool.burstcoin.ro:8080",
    "submission" : "http://pool.burstcoin.ro:8080",
    "wallet" : "http://pool.burstcoin.ro:8080"
}
```
And got this:
```
00:55:20: --------------------------------------------------
00:55:21: MWTK-BKY8-ZJ2W-37NKN: nonce found (1y 4m 14d 01:53:51)
00:55:21: 	nonce: 360206
00:55:21: 	in: /Volumes/HDD1/1893347256907199281_0_3801088_3801088
00:55:21: MWTK-BKY8-ZJ2W-37NKN: nonce on the way (1y 4m 14d 01:53:51)
00:55:21: Submit-loop 1 (1y 4m 14d 01:53:51)
00:55:21: MWTK-BKY8-ZJ2W-37NKN: nonce submitted (1y 4m 14d 01:53:51)
00:55:21: 	nonce: 360206
00:55:21: 	in /Volumes/HDD1/1893347256907199281_0_3801088_3801088
00:55:22: JSON confirmation (1y 4m 14d 01:53:51)
00:55:22: 	{"result":"success","requestProcessingTime":283,"deadline":42688431}
00:55:22: MWTK-BKY8-ZJ2W-37NKN: nonce confirmed (1y 4m 14d 01:53:51)
00:55:22: 	nonce: 360206
00:55:22: 	in /Volumes/HDD1/1893347256907199281_0_3801088_3801088
00:55:22: MiniMiner: nonce found (4m 25d 11:04:48)
00:55:22: 	nonce: 4473368
00:55:22: 	in: /Volumes/HDD2/1893347256907199281_3801088_3801088_3801088
00:55:22: MiniMiner: nonce on the way (4m 25d 11:04:48)
00:55:22: Submit-loop 1 (4m 25d 11:04:48)
00:55:22: MiniMiner: nonce submitted (4m 25d 11:04:48)
00:55:22: 	nonce: 4473368
00:55:22: 	in /Volumes/HDD2/1893347256907199281_3801088_3801088_3801088
00:55:22: JSON confirmation (4m 25d 11:04:48)
00:55:22: 	{"result":"success","requestProcessingTime":289,"deadline":12567888}
00:55:22: MiniMiner: nonce confirmed (4m 25d 11:04:48)
00:55:22: 	nonce: 4473368
00:55:22: 	in /Volumes/HDD2/1893347256907199281_3801088_3801088_3801088
```

**Comment by Creepsky** [comment]
really strange response body, what does it mean?
```
25
submitNonce & getMiningInfo API Call 
4
Only
0
```

**Comment by k06a** [comment]
@Creepsky I don't know why 80 port responded with chunked encoded text `submitNonce & getMiningInfo API Call Only`, but 8080 port have a JSON response

**Comment by k06a** [comment]
Looks like problem is solved by adding `-NDEBUG` to release configuration in `CMakeLists.txt`.

**Comment by Creepsky** [comment]
Can I merge?

**Pull request merged**
