### PR TITLE
Improve install-poco.sh script

### PR DESCRIPTION
**Pull request by theblazehen**
Run single apt-get command, don't prompt for confirmation (People should read the script before running it anyway), and run make in parallel

### CODE REVIEW

**Comment by Creepsky** [comment]
Thanks for your contribution 👍 

One thing that we should change is the installation of openssl.
Right now the shell script will only work on debian derivates, what not everyone uses.
Either we delete this line, or we add some kind of condition (if debian ... else if arch linux ... else if ...).

I think a condition would be best:

```
if [ -f /etc/debian_version ]; then
    sudo apt-get install -y openssl libssl-dev
fi
```

Other derivates can be added later on.

**Comment by Creepsky** [comment]
@theblazehen Can you please add this change?

**Comment by theblazehen** [comment]
@Creepsky I think we should remove the installing openssl part, seeing as the script is install-*poco*.sh and users should be able to easily install it from their relevant repos.

What do you think about creating a Dockerfile for it?

**Comment by Creepsky** [comment]
Agree, kick it out :)
When we already work on the script, we should also change the ./configure command.
We can omit modules from POCO that we dont need, what will result in better compile times.
`./configure --omit=Data/ODBC,Data/MySQL --no-tests --no-samples`

Dockerfile would be nice! Are you familiar with creating docker repos?

**Comment by theblazehen** [comment]
Yeah, quite familiar with it, will sort that out tonight

**Pull request merged**
